# 应用名称
spring:
  application:
    name: designMode

# 应用服务 WEB 访问端口
server:
  port: 8080
logging:
  config: classpath:logback-spring.xml
  path: ./yat/logs
  level:
    root: info
  console:
    level: info
  file:
    max-history: 30
    max-size: 100MB
    total-size-cap: 1GB